server:
  port: 8081

spring:
  application:
    name: inspectai-core-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:inspectai}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:inspectai}
    password: ${DB_PASSWORD:inspectai_dev_pass}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

ai:
  service:
    url: http://localhost:8000
